-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUrw3oGhjfWWntpO1
Z4Q+SUlmnLCUDaWB+7xhJrfYdOWgCgYIKoZIzj0DAQehRANCAAThxUGXKsQVgGGi
L+P5YPZ0PAzrYtqsVhqtliFTYIZWglyh7obdYKD4goNuUH+72DL+43c+4+PHZBzt
KxiVqEn/
-----END PRIVATE KEY-----