# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MiBook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


pod 'Alamofire', '~> 4.4'
pod 'AlamofireImage'
pod 'PureLayout'
pod 'Gallery'
pod 'ALCameraViewController'
pod 'Socket.IO-Client-Swift', '~> 13.1.0'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'AccountKit'
pod 'SwipeableTabBarController'
pod 'SwiftHash'
pod 'FBSDKLoginKit'
pod 'SDWebImage'
pod 'swiftScan'
pod 'SwiftyStarRatingView'
pod 'XMPPFramework/Swift'
pod 'DeviceUtil'

  # Pods for MiBook

end
